/** Owns round state and physics. Authored pool/HUD roots stay editable; transient balls are pooled per round. */
import {BallPitHUDUI} from './BallPitHUDUI';
import {BallPitHands} from './BallPitHands';
import {sphereMesh,boxMesh,tubeMesh} from './BallPitMesh';
import {Interactable} from 'SpectaclesInteractionKit.lspkg/Components/Interaction/Interactable/Interactable';
import {InteractionManager} from 'SpectaclesInteractionKit.lspkg/Core/InteractionManager/InteractionManager';
import {Interactor} from 'SpectaclesInteractionKit.lspkg/Core/Interactor/Interactor';
type Ball={object:SceneObject,body:BodyComponent,escaped:boolean,outside:number,interactable:Interactable};
type Grab={ball:Ball,target:SceneObject,constraint:ConstraintComponent,interactor:Interactor,side?:string,offset?:vec3};
@component
export class BallPitMain extends BaseScriptComponent {
 @input @hint('Authored pool anchor') pool:SceneObject;
 @input @hint('Passive score HUD') hud:BallPitHUDUI;
 @input @hint('Glossy plastic material') material:Material;
 @input @hint('Shared contact matter') matter:Matter;
 @input @hint('Balls per round') @widget(new SliderWidget(12,72,1)) ballCount:number=48;
 @input @hint('Pool interior width (cm)') width:number=90;
 @input @hint('Pool interior depth (cm)') depth:number=70;
 @input @hint('Rim height (cm)') rimHeight:number=18;
 @input @hint('Ball radius (cm)') ballRadius:number=5;
 @input @hint('Gravity magnitude cm/s²') gravity:number=650;
 @input @hint('Maximum physics speed cm/s') speedLimit:number=280;
 @input @hint('Ball mass kg') ballMass:number=0.045;
 @input @hint('Collision sound volume') sfxVolume:number=0.28;
 @input @hint('Music volume') musicVolume:number=0.10;
 @input @hint('Show collision wireframes') debugColliders:boolean=false;
 private balls:Ball[]=[];private grabs:Grab[]=[];private hands:BallPitHands;
 private elapsed=0;private started=false;private won=false;private ready=false;private lastImpact=-10;
 private pop:AudioComponent;private impact:AudioComponent;private victory:AudioComponent;
 private colors=[new vec4(1,0.22,0.32,1),new vec4(1,0.73,0.12,1),new vec4(0.10,0.8,1,1),new vec4(0.59,0.29,1,1),new vec4(0.3,1,0.56,1),new vec4(1,0.43,0.73,1)];
 onAwake(){const music=this.audio(requireAsset('../GeneratedSFX/BackgroundMusic.wav') as AudioTrackAsset,this.musicVolume);music.play(-1);this.impact=this.audio(requireAsset('../GeneratedSFX/PlasticImpact.wav') as AudioTrackAsset,this.sfxVolume);this.pop=this.audio(requireAsset('../GeneratedSFX/BallOut.wav') as AudioTrackAsset,this.sfxVolume);this.victory=this.audio(requireAsset('../GeneratedSFX/Victory.wav') as AudioTrackAsset,this.sfxVolume);this.createEvent('OnStartEvent').bind(()=>this.start());this.createEvent('UpdateEvent').bind(()=>this.update());}
 private start(){if(!this.pool||!this.hud||!this.material||!this.matter){console.error('[BallOut] Missing scene references');return;}const world=this.sceneObject.createComponent('Physics.WorldComponent') as WorldComponent,settings=Physics.WorldSettingsAsset.create();settings.gravity=new vec3(0,-this.gravity,0);settings.simulationRate=120;settings.absoluteSpeedLimit=this.speedLimit;settings.defaultMatter=this.matter;world.worldSettings=settings;this.ballRadius=Math.max(4,Math.min(7,this.ballRadius));this.width=Math.max(this.width,this.ballRadius*6);this.depth=Math.max(this.depth,this.ballRadius*6);this.buildPool();this.hands=new BallPitHands(this.sceneObject,this.matter,this.debugColliders,(p,side)=>this.directGrab(p,side),(p,side)=>this.directMove(p,side),side=>this.directRelease(side));this.hud.onRestart.add(()=>this.restart());this.ready=true;this.restart();console.log('[BallOut] Ready: '+this.balls.length+' physical balls; two-hand collision + pinch throw.');}
 private audio(track:AudioTrackAsset,volume:number){const a=this.sceneObject.createComponent('Component.AudioComponent') as AudioComponent;a.audioTrack=track;a.volume=volume;return a;}
 private obj(name:string,parent:SceneObject,p:vec3){const o=global.scene.createSceneObject(name);o.setParent(parent);o.getTransform().setLocalPosition(p);return o;}
 private mat(color:vec4,roughness=0.25){const m=this.material.clone();m.mainPass.baseColor=color;m.mainPass.roughness=roughness;m.mainPass.metallic=0;return m;}
 private visual(o:SceneObject,mesh:RenderMesh,m:Material){const v=o.createComponent('Component.RenderMeshVisual') as RenderMeshVisual;v.mesh=mesh;v.mainMaterial=m;}
 private slab(name:string,p:vec3,size:vec3,m:Material){const o=this.obj(name,this.pool,p);this.visual(o,boxMesh(size.x,size.y,size.z),m);const c=o.createComponent('Physics.ColliderComponent') as ColliderComponent;const s=Shape.createBoxShape();s.size=size;c.shape=s;c.matter=this.matter;c.debugDrawEnabled=this.debugColliders;}
 private buildPool(){const w=this.width,d=this.depth,h=this.rimHeight,t=20;const cyan=this.mat(new vec4(0.10,0.72,0.85,1),0.32),floor=this.mat(new vec4(0.20,0.43,0.65,1),0.55),rim=this.mat(new vec4(0.55,1,0.88,1));this.slab('Pool floor',new vec3(0,-t/2,0),new vec3(w+2*t,t,d+2*t),floor);this.slab('Left wall',new vec3(-(w+t)/2,h/2,0),new vec3(t,h,d+2*t),cyan);this.slab('Right wall',new vec3((w+t)/2,h/2,0),new vec3(t,h,d+2*t),cyan);this.slab('Back wall',new vec3(0,h/2,-(d+t)/2),new vec3(w,h,t),cyan);this.slab('Front wall',new vec3(0,h/2,(d+t)/2),new vec3(w,h,t),cyan);
 const points:vec3[]=[];const hw=w/2+10,hd=d/2+10,cr=10;for(let corner=0;corner<4;corner++){const cx=corner===0||corner===3?hw-cr:-hw+cr,cz=corner<2?hd-cr:-hd+cr;for(let i=0;i<10;i++){const a=(corner*90+i*10)*Math.PI/180;points.push(new vec3(cx+cr*Math.cos(a),h,cz+cr*Math.sin(a)));}}const ring=this.obj('Mint rounded safety rim',this.pool,vec3.zero());this.visual(ring,tubeMesh(points,3.4),rim);
 }
 public restart(){for(const g of this.grabs.slice())this.release(g.ball);for(const b of this.balls)b.object.destroy();this.balls=[];this.started=false;this.elapsed=0;this.won=false;const r=this.ballRadius,spacing=r*2+1,cols=Math.max(1,Math.floor((this.width-2*r)/spacing)),rows=Math.max(1,Math.floor((this.depth-2*r)/spacing)),mesh=sphereMesh(r),mats=this.colors.map(c=>this.mat(c));const count=Math.min(72,Math.max(1,Math.floor(this.ballCount)));for(let i=0;i<count;i++){const x=i%cols,z=Math.floor(i/cols)%rows,layer=Math.floor(i/(cols*rows));const o=this.obj('Ball '+(i+1).toString().padStart(2,'0'),this.pool,new vec3((x-(cols-1)/2)*spacing,r+0.6+layer*spacing,(z-(rows-1)/2)*spacing));this.visual(o,mesh,mats[i%mats.length]);const body=o.createComponent('Physics.BodyComponent') as BodyComponent;const shape=Shape.createSphereShape();shape.radius=r;body.shape=shape;body.mass=this.ballMass;body.damping=0.07;body.angularDamping=0.08;body.matter=this.matter;body.debugDrawEnabled=this.debugColliders;const interactable=o.createComponent(Interactable.getTypeName()) as Interactable;interactable.targetingMode=3;InteractionManager.getInstance().deregisterInteractable(interactable);interactable.colliders=[body];InteractionManager.getInstance().registerInteractable(interactable);const ball:Ball={object:o,body,escaped:false,outside:0,interactable};this.balls.push(ball);interactable.onTriggerStart.add(e=>this.grab(ball,e.interactor));interactable.onDragUpdate.add(e=>{const g=this.grabs.find(g=>g.ball===ball);if(g){const delta=e.planecastDragVector??e.dragVector;g.target.getTransform().setWorldPosition(g.target.getTransform().getWorldPosition().add(delta));}});interactable.onTriggerEnd.add(()=>this.release(ball));interactable.onTriggerCanceled.add(()=>this.release(ball));body.onCollisionEnter.add(()=>{if(!this.started||getTime()-this.lastImpact<0.12||body.velocity.length<28)return;this.lastImpact=getTime();this.impact.play(1);});}this.hud.setProgress(count,count,0,false,false);}
 private grab(b:Ball,i:Interactor){if(b.escaped||this.grabs.some(g=>g.ball===b))return;this.started=true;const p=b.object.getTransform().getWorldPosition(),target=this.obj('Grab anchor',this.sceneObject,p);target.getTransform().setWorldPosition(p);const c=target.createComponent('Physics.ColliderComponent') as ColliderComponent;const s=Shape.createSphereShape();s.radius=0.1;c.shape=s;c.intangible=true;c.clearMotion();const constraint=b.body.addPointConstraint(c,p);constraint.linkedBodyCollisionEnabled=false;this.grabs.push({ball:b,target,constraint,interactor:i});}
 private directGrab(p:vec3,side:string){this.directRelease(side);let nearest:Ball=null,dist=this.ballRadius+9;for(const b of this.balls){if(b.escaped||this.grabs.some(g=>g.ball===b))continue;const d=b.object.getTransform().getWorldPosition().distance(p);if(d<dist){dist=d;nearest=b;}}if(nearest){this.grab(nearest,null);const g=this.grabs.find(g=>g.ball===nearest);if(g){g.side=side;g.offset=g.target.getTransform().getWorldPosition().sub(p);}}}
 private directMove(p:vec3,side:string){const g=this.grabs.find(g=>g.side===side);if(g)g.target.getTransform().setWorldPosition(p.add(g.offset));}
 private directRelease(side:string){const g=this.grabs.find(g=>g.side===side);if(g)this.release(g.ball);}
 private release(b:Ball){const index=this.grabs.findIndex(g=>g.ball===b);if(index<0)return;const g=this.grabs[index];b.body.removeConstraint(g.constraint);g.target.destroy();this.grabs.splice(index,1);}
 private update(){if(!this.ready)return;const tracked=this.hands.update();const dt=Math.min(getDeltaTime(),0.05);if(this.started&&!this.won)this.elapsed+=getDeltaTime();let remaining=0;const inv=this.pool.getTransform().getInvertedWorldTransform();for(const b of this.balls){if(b.escaped)continue;const p=inv.multiplyPoint(b.object.getTransform().getWorldPosition());const out=Math.abs(p.x)>this.width/2+20+this.ballRadius||Math.abs(p.z)>this.depth/2+20+this.ballRadius;if(out){b.outside+=dt;if(b.outside>0.25){b.escaped=true;this.release(b);this.pop.play(1);if(!this.started)this.started=true;continue;}}else b.outside=0;if(tracked&&b.body.velocity.length>35)this.started=true;if(p.y < -100){b.object.getTransform().setLocalPosition(new vec3(0,this.rimHeight+this.ballRadius*2,0));b.body.clearMotion();}remaining++;}if(remaining===0&&!this.won){this.won=true;this.victory.play(1);console.log('[BallOut] Pool cleared in '+this.elapsed.toFixed(1)+' seconds');}for(const b of this.balls){if(b.escaped&&b.object.enabled&&b.object.getTransform().getWorldPosition().y < -200)b.object.enabled=false;}this.hud.setProgress(remaining,this.balls.length,this.elapsed,this.won,this.started);}
}
